<script context="module">
	export const metadata = {"title":"Factorial! Race!","description":"Finding an upper limit on factorials in JavaScript","date":"2021.06.07","slug":"factorial-race","type":"text, texts"};
	const { title, description, date, slug, type } = metadata;
</script>
<script>
  import Introduction from '../components/Introduction.svelte'
</script>


<Introduction {metadata} />
<p>For the past while now, I’ve been tinkering on <a
  href="https://www.dicegraph.com/"
  rel="nofollow"
>a side project</a> that builds and graphs arbitrary probability distributions created by dice rolling outcomes. It’s extremely niche and dorky, but it’s a been a really fun way to explore both product design development and new concepts in math and programming that have otherwise never presented themselves during my career.</p>
<p>This is an article about the second bit.</p>
<p>One of the interesting things that I discovered early on was that when adding the ability to <em>multiply and reduce</em> dice rather than just <em>multiply or reduce</em> dice (ie; roll 1d6, roll the resulting number of dice, on a 4 or higher roll again, sum the total results. Complicated!) the distributions are <a
  href="https://en.wikipedia.org/wiki/Normal_distribution"
  rel="nofollow"
>not normal</a>, which means in order to actually graph the distribution we need to calculate every possible outcome. Not a big deal, since computers are good at this sort of stuff!</p>
<p>However, I quickly discovered an upper bound: the calculation requires working with <a
  href="https://en.wikipedia.org/wiki/Factorial"
  rel="nofollow"
>factorials</a>. When the factorials get big, JavaScript gives up and returns <code>Infinity</code>. This is because there is <a
  href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER"
  rel="nofollow"
>a maximum limit</a> to the size of a double-precision floating-point number that JS uses for the <code>Number</code> type. Wow, this got both mathy and programmery really quickly.</p>
<p>This gave us an upper bound of <code>170!</code>, since the rest of the distribution calculations don’t like it when you pass them <code>Infinity</code>.</p>
<pre class="language-js">{@html `<code class="language-js"><span class="token keyword">const</span> <span class="token function-variable function">factorial</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">x</span><span class="token punctuation">)</span> <span class="token operator">=></span> x <span class="token operator">></span> <span class="token number">1</span> <span class="token operator">?</span> x <span class="token operator">*</span> <span class="token function">factorial</span><span class="token punctuation">(</span>x <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token number">1</span>
<span class="token function">factorial</span><span class="token punctuation">(</span><span class="token number">170</span><span class="token punctuation">)</span> <span class="token comment">// 7.257415615307994e+306</span>
<span class="token function">factorial</span><span class="token punctuation">(</span><span class="token number">171</span><span class="token punctuation">)</span> <span class="token comment">// Infinity</span></code>`}</pre>
<p>Lucky for us, JavaScript has implemented a <a
  href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt"
  rel="nofollow"
>Big Integer</a> type for integers that are … well … big! I was able to refactor my <code>factorial</code> function to use <code>BigInt</code>s.</p>
<pre class="language-js">{@html `<code class="language-js"><span class="token keyword">const</span> <span class="token function-variable function">big_factorial</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">x</span><span class="token punctuation">)</span> <span class="token operator">=></span> x <span class="token operator">></span> <span class="token number">1</span> <span class="token operator">?</span> x <span class="token operator">*</span> <span class="token function">big_factorial</span><span class="token punctuation">(</span>x <span class="token operator">-</span> <span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span>
<span class="token function">big_factorial</span><span class="token punctuation">(</span><span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">171</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 1241018070217667823424840524103103992616605577501693185388951803611996075221691752992751978120487585576464959501670387052809889858690710767331242032218484364310473577889968548278290754541561964852153468318044293239598173696899657235903947616152278558180061176365108428800000000000000000000000000000000000000000n</span></code>`}</pre>
<p>So what’s our new upper bound? We can handle <code>170!</code> easily, how high can we go? <code>1,000!</code>? <code>10,000!</code>?</p>
<pre class="language-js">{@html `<code class="language-js"><span class="token function">big_factorial</span><span class="token punctuation">(</span><span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 402387260…0n</span>
<span class="token function">big_factorial</span><span class="token punctuation">(</span><span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">10000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// RangeError: Maximum call stack size exceeded</span></code>`}</pre>
<p>Turns out <code>1,000!</code> is a walk in the park. <code>10,000!</code> gets a little more interesting! The error that returns on the function is about <a
  href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Too_much_recursion"
  rel="nofollow"
>too much recursion</a>. We’re calling <code>big_factorial</code> <em>from</em> <code>big_factorial</code> ten thousand times and the browser thinks this means something is wrong, so it bails out on the process.</p>
<p>So, what if we refactor our recursive <code>big_factorial</code> to use a loop?</p>
<pre class="language-js">{@html `<code class="language-js"><span class="token keyword">const</span> <span class="token function-variable function">big_fast_factorial</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">x</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">&#123;</span>
  <span class="token keyword">let</span> r <span class="token operator">=</span> <span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span> i <span class="token operator">&lt;=</span> x<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span>
    r <span class="token operator">=</span> r <span class="token operator">*</span> i<span class="token punctuation">;</span>
  <span class="token keyword">return</span> r<span class="token punctuation">;</span>
<span class="token punctuation">&#125;</span>
<span class="token function">big_fast_factorial</span><span class="token punctuation">(</span><span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">10000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 284625…0n in about 70ms</span></code>`}</pre>
<p><code>10,000!</code> is fast! We can get reliably get the result of that in less than 100ms. And since our loop will run as long as it needs to, our upper bound should now be based on compute and return time, rather than type errors or browser guardrails. Lets see what we can do now:</p>
<pre class="language-js">{@html `<code class="language-js"><span class="token function">big_fast_factorial</span><span class="token punctuation">(</span><span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">20000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// ~300ms</span>
<span class="token function">big_fast_factorial</span><span class="token punctuation">(</span><span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">30000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// ~650ms</span>
<span class="token comment">// …</span>
<span class="token function">big_fast_factorial</span><span class="token punctuation">(</span><span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">90000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// ~7238ms</span>
<span class="token function">big_fast_factorial</span><span class="token punctuation">(</span><span class="token function">BigInt</span><span class="token punctuation">(</span><span class="token number">100000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// ~9266ms</span></code>`}</pre>
<p>Things … start to get slow above 30 or 40 thousand factorial. Every additional ten thousand to our initial number adds more and more time to the compute function. Im sure theres some fancy <code>O(n)</code> complexity notation to express this, but I don’t really want to figure that out. It’s too slow to use an in a UI above say, <code>50,000!</code>.</p>
<p>Turns out tho, even mathematicians don’t really calculate factorials this big. They use <a
  href="https://en.wikipedia.org/wiki/Stirling%27s_approximation"
  rel="nofollow"
>Stirlings’ Approximation</a> instead, since it’s faster and “good enough”. It looks sort of like this:</p>
<pre class="language-undefined">{@html `<code class="language-undefined">𝑒ln(𝑛!) = 𝑛!
where
ln(𝑛!) = ∑𝑛𝑘=1(ln𝑛)</code>`}</pre>
<p>It would be pretty cool to do this in JavaScript! And personally, I love “good enough”. I’ve already got a handy function for running Big Sigma calculations:</p>
<pre class="language-js">{@html `<code class="language-js"><span class="token keyword">const</span> <span class="token function-variable function">new_arr</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">s<span class="token punctuation">,</span>n</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">&#123;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>s <span class="token operator">&lt;</span> <span class="token number">0</span> <span class="token operator">||</span> n <span class="token operator">&lt;</span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">&#123;</span> <span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">&#125;</span>
  <span class="token keyword">return</span> Array<span class="token punctuation">.</span><span class="token function">from</span><span class="token punctuation">(</span><span class="token function">Array</span><span class="token punctuation">(</span>n<span class="token operator">+</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">keys</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span><span class="token parameter">v</span> <span class="token operator">=></span> v <span class="token operator">></span> s<span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span>
<span class="token punctuation">&#125;</span>

<span class="token keyword">const</span> <span class="token function-variable function">Σ</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">min<span class="token punctuation">,</span> max<span class="token punctuation">,</span> fn</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">new_arr</span><span class="token punctuation">(</span>min<span class="token punctuation">,</span> max<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">reduce</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">acc<span class="token punctuation">,</span> val</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">fn</span><span class="token punctuation">(</span>val<span class="token punctuation">)</span> <span class="token operator">+</span> acc<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span></code>`}</pre>
<p>So lets try this out:</p>
<pre class="language-js">{@html `<code class="language-js"><span class="token keyword">const</span> <span class="token function-variable function">log</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">x</span><span class="token punctuation">)</span> <span class="token operator">=></span> Math<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>x<span class="token punctuation">)</span>
Math<span class="token punctuation">.</span><span class="token function">exp</span><span class="token punctuation">(</span><span class="token function">Σ</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1000000</span><span class="token punctuation">,</span> log<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// Infinity</span></code>`}</pre>
<p>Oh no! The end result of our <code>1,000,000!</code> function <em>is still Infinity</em>. Thats because one million factorial is … very big. It could still fit into a <code>BigInt</code>, but then we have another problem: we cant run <code>Math</code> functions on the <code>BigInt</code> type. And we can’t rewrite the functions to use <code>BigInt</code>s because the type is, by definition, <em>only for integers</em>. and <code>𝑒</code> is definitely not an integer. Even a math library like <a
  href="https://mathjs.org/"
  rel="nofollow"
>math.js</a> has the same issues around typing, despite trying to account for it.</p>
<p>Naturally, this leads to a simple proposal: FaaStorials! Fast Factorials as a Service! Since factorials are immutable, it should be possible to store the first 1,000,000 or so in a database, and provide an API for querying and returning them. Even a slow network request would be faster than computing the factorial locally. It should be possible to crunch (slowly) all the factorials, and write them to a database for retrieval on demand. I wrote this function and got about 7,000 rows written before I realized it would probably be expensive.</p>
<p>According to my rough estimating, <code>1,000,000!</code> would send a response that weights about <code>700kb</code>, and the whole database would be in the neighborhood of <code>350gb</code>. This would cost me about $80 a month to store, maybe $100 a month to pay for the requests as well. I pulled the plug on the script.</p>
<p>As with many problems, the upper bound ends up being defined by time and money, the end!</p>
