/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "svelte/internal";

function create_fragment(ctx) {
	let p;

	return {
		c() {
			p = element("p");

			p.innerHTML = `<img src="./content.png" alt="content"> 
<img src="./layer.png" alt="layer"> 
<img src="./data.png" alt="data"> 
<img src="./rendering.png" alt="rendering"> 
<img src="./search.png" alt="search">`;
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

const metadata = {
	"title": "ArcGIS Online",
	"date": "2015.10.31",
	"slug": "arcgis-online",
	"site": "https://www.arcgis.com/",
	"description": "Designing, prototyping, and developing the web platform for the worlds leading GIS software.",
	"type": "projects, esri"
};

const { title, date, slug, site, description, type } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
export { metadata };