/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "svelte/internal";

function create_fragment(ctx) {
	let p0;
	let t0;
	let h20;
	let t2;
	let p1;
	let t7;
	let p2;
	let t19;
	let p3;
	let t20;
	let h21;
	let t22;
	let p4;
	let t24;
	let p5;
	let t27;
	let p6;
	let t30;
	let p7;
	let t33;
	let p8;
	let t36;
	let p9;
	let t41;
	let p10;
	let t44;
	let p11;
	let t45;
	let h22;
	let t47;
	let p12;
	let t51;
	let pre;

	let raw_value = `<code class="language-undefined">@mixin tab-contents() &#123;
  @include box-sizing(border-box);
  border: 1px solid $lighter-gray;
  margin-top: -1px;
&#125;
@if $include-tabs == true &#123;
 .tab-section &#123; @include tab-section(); &#125;
&#125;</code>` + "";

	let t52;
	let p13;
	let t55;
	let h23;
	let t57;
	let p14;
	let t65;
	let p15;
	let t66;
	let p16;
	let t70;
	let p17;
	let t71;
	let h24;
	let t73;
	let p18;
	let t77;
	let p19;
	let t78;
	let h25;
	let t80;
	let p20;

	return {
		c() {
			p0 = element("p");
			p0.innerHTML = `<img src="https://photos.smugmug.com/Projects/Calcite-web/i-FNjrvmC/0/1db11e90/X3/title-X3.png" alt="Calite Web Homepage">`;
			t0 = space();
			h20 = element("h2");
			h20.textContent = "Design System, Development Framework";
			t2 = space();
			p1 = element("p");
			p1.innerHTML = `<a href="http://www.esri.com/about-esri" rel="nofollow">Esri</a> is a large, international technology company with development teams all over the world — from Portland to Glasgow to Zurich to Beijing. Esri’s <em>design</em> team however, is based in the Redlands, California mother-ship. This meant that a lot of the design tools created for Esri’s web presence were unevenly distributed across the huge number of teams who needed to develop web properties.`;
			t7 = space();
			p2 = element("p");
			p2.innerHTML = `At <a href="http://pdx.esri.com/" rel="nofollow">Esri PDX R&amp;D</a> we had <a href="http://paulcpederson.com/" rel="nofollow">assembled</a> a <a href="http://patrickarlt.com/" rel="nofollow">strong</a>  <a href="http://ungoldman.com/" rel="nofollow">team</a> of designer/developers. We sat down to create a design system that we could distribute to <em>all</em> of Esri’s development teams, with the goal of creating a unified user experience for all our customers, and keeping all of our properties aligned and in sync as we moved forward.`;
			t19 = space();
			p3 = element("p");
			p3.innerHTML = `<img src="https://photos.smugmug.com/Projects/Calcite-web/i-ddZ8k6m/0/e1ea0445/X3/examples-doc-X3.png" alt="Calcite Web Examples">`;
			t20 = space();
			h21 = element("h2");
			h21.textContent = "Goals";
			t22 = space();
			p4 = element("p");
			p4.textContent = "Building a design library and CSS framework can be a complicated affair, made more complicated by the large audience of developers we had to make the project work for.";
			t24 = space();
			p5 = element("p");
			p5.innerHTML = `<strong>Adoption:</strong> We had to make the framework incredibly attractive to Esri developers, and incredible easy for them to use. Our main goal was unification, so any barriers to adoption needed to be removed.`;
			t27 = space();
			p6 = element("p");
			p6.innerHTML = `<strong>Composabillity:</strong> To this end, we needed using the framework to be as simple is including a CSS file and copy-pasting code samples.`;
			t30 = space();
			p7 = element("p");
			p7.innerHTML = `<strong>Modularity:</strong> Many of the projects at Esri have rigid, preexisting code bases and technologies that we needed to integrate smoothly with — we needed to provide a system that works in whatever tech stack it finds itself in.`;
			t33 = space();
			p8 = element("p");
			p8.innerHTML = `<strong>No Opinions:</strong> We wanted the framework to provide a full set of interactive patterns — requiring JavaScript — but also work in any JavaScript framework environment.`;
			t36 = space();
			p9 = element("p");
			p9.innerHTML = `<strong>Robust:</strong> Certain aspects of the framework — like <a href="/projects/viewport-grid">the grid system</a> had major functional requirements. The grid itself needed to be column based, fully responsive by default, and work down to IE 8.`;
			t41 = space();
			p10 = element("p");
			p10.innerHTML = `<strong>Flexible:</strong> Developers needed to have access to a wide range of patterns, ensuring that common structures didn’t get independently invented in different projects. Designers needed to have the freedom to create on-off pages that stood out without feeling constricted.`;
			t44 = space();
			p11 = element("p");
			p11.innerHTML = `<img src="https://photos.smugmug.com/Projects/Calcite-web/i-RtQW5gB/0/e5bee077/X3/patterns-doc-X3.png" alt="Calcite Web Patterns">`;
			t45 = space();
			h22 = element("h2");
			h22.textContent = "Using Sass";
			t47 = space();
			p12 = element("p");
			p12.innerHTML = `Sass — through the <a href="https://github.com/sass/node-sass" rel="nofollow">Node Sass project</a> allowed us to meet many of our goals. A major theoretical underpinning to the framework’s .SCSS involved making the specificity graph as flat as possible, and decoupling style code from selectors. This allows the design code to be reused and adapted basically anywhere in any given project.`;
			t51 = space();
			pre = element("pre");
			t52 = space();
			p13 = element("p");
			p13.innerHTML = `The CSS development principles are outlined in <a href="http://paulcpederson.com/articles/css-for-people-who-hate-css/" rel="nofollow">an excellent article (and Esri User Conference presentation) by Paul Pederson.</a>`;
			t55 = space();
			h23 = element("h2");
			h23.textContent = "JavaScript, or Not";
			t57 = space();
			p14 = element("p");
			p14.innerHTML = `All of our interactive patterns require a <code>.js-</code> prefix hook to bind JS events too. This lets projects using <a href="https://angularjs.org/" rel="nofollow">Angular</a> or <a href="https://facebook.github.io/react/" rel="nofollow">React</a> to write their own component code for the interactions while still getting all the canonical design code for a pattern.`;
			t65 = space();
			p15 = element("p");
			p15.innerHTML = `<img src="https://photos.smugmug.com/Projects/Calcite-web/i-nJkf5G2/0/abe4593b/X3/event-bus-doc-X3.png" alt="Calcite Web Patterns">`;
			t66 = space();
			p16 = element("p");
			p16.innerHTML = `The JS portion of the framework uses Publication / Subscription event bus to connect user intent and component behavior. This allows for programmatic control of the UI, and lets a pattern communicate to the rest of the application. The JavaScript library is written as a set of ES6 modules, and is compiled to an ES5 UMD module, attaching itself to the <code>window</code> on load.`;
			t70 = space();
			p17 = element("p");
			p17.innerHTML = `<img src="https://photos.smugmug.com/Projects/Calcite-web/i-npTCL4g/0/705a3306/X3/color-doc-X3.png" alt="Calcite Web Grayscale">`;
			t71 = space();
			h24 = element("h2");
			h24.textContent = "The Brand";
			t73 = space();
			p18 = element("p");
			p18.innerHTML = `Color and Typography do most of the heavy lifting when communicated brand identity on the Web. We developed a gray scale, and selected a limited set of colors from the immense set of <a href="https://github.com/Esri/calcite-colors" rel="nofollow">Esri’s color pallete</a> to expose as simple color classes and variables. We updated the typography to Avenir NExt by Adrian Frutiger and Akira Kobayashi to give Esri’s classic Avenir print style a boost that it needed for screen display.`;
			t77 = space();
			p19 = element("p");
			p19.innerHTML = `<img src="https://photos.smugmug.com/Projects/Calcite-web/i-9Gp8DGk/0/3575a9d5/X3/type-doc-X3.png" alt="Calcite Web Type">`;
			t78 = space();
			h25 = element("h2");
			h25.textContent = "Conclusion";
			t80 = space();
			p20 = element("p");
			p20.innerHTML = `The framework as been very successful so far — being integrated into new designs for esri.com, new sections of <a href="http://www.arcgis.com/home/item.html?id=52bdc7ab7fb044d98add148764eaa30a" rel="nofollow">ArcGIS Online</a>, and a number of <a href="https://developers.arcgis.com/" rel="nofollow">related ArcGIS properties</a>.`;
			attr(pre, "class", "language-undefined");
		},
		m(target, anchor) {
			insert(target, p0, anchor);
			insert(target, t0, anchor);
			insert(target, h20, anchor);
			insert(target, t2, anchor);
			insert(target, p1, anchor);
			insert(target, t7, anchor);
			insert(target, p2, anchor);
			insert(target, t19, anchor);
			insert(target, p3, anchor);
			insert(target, t20, anchor);
			insert(target, h21, anchor);
			insert(target, t22, anchor);
			insert(target, p4, anchor);
			insert(target, t24, anchor);
			insert(target, p5, anchor);
			insert(target, t27, anchor);
			insert(target, p6, anchor);
			insert(target, t30, anchor);
			insert(target, p7, anchor);
			insert(target, t33, anchor);
			insert(target, p8, anchor);
			insert(target, t36, anchor);
			insert(target, p9, anchor);
			insert(target, t41, anchor);
			insert(target, p10, anchor);
			insert(target, t44, anchor);
			insert(target, p11, anchor);
			insert(target, t45, anchor);
			insert(target, h22, anchor);
			insert(target, t47, anchor);
			insert(target, p12, anchor);
			insert(target, t51, anchor);
			insert(target, pre, anchor);
			pre.innerHTML = raw_value;
			insert(target, t52, anchor);
			insert(target, p13, anchor);
			insert(target, t55, anchor);
			insert(target, h23, anchor);
			insert(target, t57, anchor);
			insert(target, p14, anchor);
			insert(target, t65, anchor);
			insert(target, p15, anchor);
			insert(target, t66, anchor);
			insert(target, p16, anchor);
			insert(target, t70, anchor);
			insert(target, p17, anchor);
			insert(target, t71, anchor);
			insert(target, h24, anchor);
			insert(target, t73, anchor);
			insert(target, p18, anchor);
			insert(target, t77, anchor);
			insert(target, p19, anchor);
			insert(target, t78, anchor);
			insert(target, h25, anchor);
			insert(target, t80, anchor);
			insert(target, p20, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p0);
			if (detaching) detach(t0);
			if (detaching) detach(h20);
			if (detaching) detach(t2);
			if (detaching) detach(p1);
			if (detaching) detach(t7);
			if (detaching) detach(p2);
			if (detaching) detach(t19);
			if (detaching) detach(p3);
			if (detaching) detach(t20);
			if (detaching) detach(h21);
			if (detaching) detach(t22);
			if (detaching) detach(p4);
			if (detaching) detach(t24);
			if (detaching) detach(p5);
			if (detaching) detach(t27);
			if (detaching) detach(p6);
			if (detaching) detach(t30);
			if (detaching) detach(p7);
			if (detaching) detach(t33);
			if (detaching) detach(p8);
			if (detaching) detach(t36);
			if (detaching) detach(p9);
			if (detaching) detach(t41);
			if (detaching) detach(p10);
			if (detaching) detach(t44);
			if (detaching) detach(p11);
			if (detaching) detach(t45);
			if (detaching) detach(h22);
			if (detaching) detach(t47);
			if (detaching) detach(p12);
			if (detaching) detach(t51);
			if (detaching) detach(pre);
			if (detaching) detach(t52);
			if (detaching) detach(p13);
			if (detaching) detach(t55);
			if (detaching) detach(h23);
			if (detaching) detach(t57);
			if (detaching) detach(p14);
			if (detaching) detach(t65);
			if (detaching) detach(p15);
			if (detaching) detach(t66);
			if (detaching) detach(p16);
			if (detaching) detach(t70);
			if (detaching) detach(p17);
			if (detaching) detach(t71);
			if (detaching) detach(h24);
			if (detaching) detach(t73);
			if (detaching) detach(p18);
			if (detaching) detach(t77);
			if (detaching) detach(p19);
			if (detaching) detach(t78);
			if (detaching) detach(h25);
			if (detaching) detach(t80);
			if (detaching) detach(p20);
		}
	};
}

const metadata = {
	"title": "Calcite Web",
	"slug": "calcite-web",
	"site": "http://esri.github.io/calcite-web",
	"date": "2015.11.25",
	"description": "A framework that addresses common design problems and interactive elements for Esri, creating a united visual language and user experience.",
	"type": "projects, esri"
};

const { title, slug, site, date, description, type } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
export { metadata };