/* generated by Svelte v3.24.0 */
import { SvelteComponent, init, safe_not_equal } from "svelte/internal";

const metadata = {
	"title": "An Empty Room V",
	"slug": "empty-room-v",
	"source": "https://photos.smugmug.com/Prints/Prints/i-K3KMsx8/0/49163269/XL/empty-room-5-800-XL.png",
	"alt": "Black and white Risograph with halftone dots depecting an empty room, a small closet in the foreground.",
	"description": "One layer Risograph on Stonehenge Cream \\#110",
	"date": "2017.01.05",
	"edition": 10,
	"size": "5x5 inches.",
	"media": "Risograph",
	"type": "art, risograph, edition"
};

const { title, slug, source, alt, description, date, edition, size, media, type } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { metadata };