/* generated by Svelte v3.24.0 */
import { SvelteComponent, init, safe_not_equal } from "svelte/internal";

const metadata = {
	"title": "An Empty Room II",
	"slug": "empty-room-ii",
	"source": "https://photos.smugmug.com/Prints/Prints/i-swpfRT6/0/afe88f66/XL/empty-room-2-800-XL.png",
	"alt": "Black and white Risograph with halftone dots, looking down a hallway into a kitchen with a diamond floor pattern.",
	"description": "One layer Risograph on Stonehenge Cream \\#110",
	"date": "2017.01.02",
	"edition": 10,
	"size": "5x5 inches.",
	"media": "Risograph",
	"type": "art, risograph, edition"
};

const { title, slug, source, alt, description, date, edition, size, media, type } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { metadata };