/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "svelte/internal";

function create_fragment(ctx) {
	let h30;
	let t1;
	let p0;
	let t7;
	let p1;
	let t15;
	let p2;
	let t17;
	let p3;
	let t18;
	let h31;
	let t20;
	let p4;
	let t22;
	let p5;
	let t25;
	let p6;
	let t28;
	let p7;
	let t37;
	let p8;
	let t40;
	let p9;
	let t45;
	let p10;
	let t50;
	let p11;
	let t51;
	let h32;
	let t53;
	let p12;
	let t64;
	let p13;
	let t65;
	let p14;
	let t67;
	let p15;
	let t68;
	let h33;
	let t70;
	let p16;
	let t72;
	let p17;
	let t73;
	let p18;

	return {
		c() {
			h30 = element("h3");
			h30.textContent = "Concept";
			t1 = space();
			p0 = element("p");
			p0.innerHTML = `I’ve been playing Go (poorly) for the past 10 years or so ( on and off), so when <a href="http://paulcpederson.com/" rel="nofollow">Paul</a> asked me if I knew how to play after the recent <a href="">triumph of AlphaGo</a> over Lee Sedol, 9 Dan, I was pretty excited to have an opponent. Paul learned the game quick and soon was playing at my level (and slightly above!). We played over lunch, and one day when we were both working from home rather than the office, we decided to see what was out there for playing online.`;
			t7 = space();
			p1 = element("p");
			p1.innerHTML = `While there are some amazing servers out there for playing Go like <a href="https://online-go.com/" rel="nofollow">Online Go</a>, <a href="https://www.gokgs.com/" rel="nofollow">KGS</a>, and <a href="http://www.tygembaduk.com/" rel="nofollow">Tygem Baduk</a>, they all required a significant amount of set up, investment, and it was tricky for us to just pick up a game with each other right away. What we needed was a Go server where one player could send a URL to the other and start playing.`;
			t15 = space();
			p2 = element("p");
			p2.textContent = "So we built that!";
			t17 = space();
			p3 = element("p");
			p3.innerHTML = `<img src="https://photos.smugmug.com/Projects/Joseki-party/i-StZmkMS/0/4fb63fac/X3/title-X3.png" alt="Title Screen for Joseki Party">`;
			t18 = space();
			h31 = element("h3");
			h31.textContent = "The Big Idea";
			t20 = space();
			p4 = element("p");
			p4.textContent = "We had a couple of hard requirements for the project, which shaped a lot of our design decisions.";
			t22 = space();
			p5 = element("p");
			p5.innerHTML = `<strong>No Auth:</strong> We wanted to avoid any sort of user account management — no creating accounts, no signing in, no OAuth with Twitter or Facebook so you can share post your game points. This was going to be about zero-friction Go. Any set up where a user has to do anything beyond start playing when they got a link was off the table.`;
			t25 = space();
			p6 = element("p");
			p6.innerHTML = `<strong>No Server:</strong> Paul and I are front-end types — we both know plenty of NodeJS but dislike writing servers. This was going to be pure client-side.`;
			t28 = space();
			p7 = element("p");
			p7.innerHTML = `<strong>No Framework:</strong> There’s been a <em>lot</em> of discourse about the state of JavaScript frameworks in 2016. And after using any number of different frameworks for any number of projects (and one notable example of 4 frameworks in <em>one</em> project) I thought we could experiment with <a href="http://vanilla-js.com/" rel="nofollow">Vanills JS</a> and see where that landed us.`;
			t37 = space();
			p8 = element("p");
			p8.innerHTML = `<strong>Live:</strong> It’s a game, so we decided it should feel as close as possible to sitting down and playing a game. We wanted to avoid browser refreshes, notifications, and things of that nature. When you play, your opponent sees the move. When your opponent plays, you see the move.`;
			t40 = space();
			p9 = element("p");
			p9.innerHTML = `<strong>MVI Loops:</strong> A major part of the project was getting deep into the practicalities of writing <a href="http://staltz.com/unidirectional-user-interface-architectures.html" rel="nofollow">unidirectional applications</a> with a Model → View → Intent system.`;
			t45 = space();
			p10 = element("p");
			p10.innerHTML = `<strong>A New Visual Language:</strong> One of my major design interests is in the translation between the analog and the digital. I wanted to take the same approach to the aesthetics of Go — attempt the keep the striking nature of the game itself but ditch any attempt at skeuomorphism that pervades practically <em>all</em> of the computer Go programs I’ve ever played on.`;
			t50 = space();
			p11 = element("p");
			p11.innerHTML = `<img src="https://photos.smugmug.com/Projects/Joseki-party/i-dwf5h8p/0/ca9e4700/X3/new-game-X3.png" alt="Starting a New Game">`;
			t51 = space();
			h32 = element("h3");
			h32.textContent = "Solutions";
			t53 = space();
			p12 = element("p");
			p12.innerHTML = `<strong><a href="https://firebase.google.com/" rel="nofollow">Firebase</a></strong> solved a lot of our problems with the practicalities of a shared, live game state without using a server. We decided on generating random names for games, and saving the model of the game state under those keys in a single Firebase project. The NPM project <strong><a href="https://www.npmjs.com/package/weiqi" rel="nofollow">Weiqi by cjlarose</a></strong> provided the essential client-side tools for manipulating the game, with a small addition in a <strong><a href="https://github.com/nikolaswise/weiqi.js" rel="nofollow">fork of the project</a></strong> to add a method for removing dead stones from the board before scoring. <strong><a href="https://surge.sh/" rel="nofollow">Surge</a></strong> provides the hosting, and their excellent <strong><a href="https://surge.sh/help/adding-a-200-page-for-client-side-routing" rel="nofollow">client side routing</a></strong> allowed us to make the whole thing a single page app.`;
			t64 = space();
			p13 = element("p");
			p13.innerHTML = `<img src="https://photos.smugmug.com/Projects/Joseki-party/i-N2Lk3cW/0/f7eece08/X3/opening-X3.png" alt="Opening State">`;
			t65 = space();
			p14 = element("p");
			p14.textContent = "The client side routing lets us provide a single link to Black, White, or a neutral observer who just wants to watch the game unfold.";
			t67 = space();
			p15 = element("p");
			p15.innerHTML = `<img src="https://photos.smugmug.com/Projects/Joseki-party/i-DzVDfMH/0/b867008a/X3/gameplay-X3.png" alt="Playing the Game">`;
			t68 = space();
			h33 = element("h3");
			h33.textContent = "The Fun Parts";
			t70 = space();
			p16 = element("p");
			p16.textContent = "Exploring different aesthetics that our game board could take was a real interesting undertaking — one that is still ongoing. With the perpetually fluid nature of the web, we can create any number of wildly unorthodox color schemes.";
			t72 = space();
			p17 = element("p");
			p17.innerHTML = `<img src="https://photos.smugmug.com/Projects/Joseki-party/i-C8sbxnC/0/XL/changing-scheme-XL.jpg" alt="Changing the Color Scheme">`;
			t73 = space();
			p18 = element("p");
			p18.textContent = "So send me a link if you want to play! I’ve been playing nothing but 13x13 lately, so start a bigger game and I’ll probably be toast.";
		},
		m(target, anchor) {
			insert(target, h30, anchor);
			insert(target, t1, anchor);
			insert(target, p0, anchor);
			insert(target, t7, anchor);
			insert(target, p1, anchor);
			insert(target, t15, anchor);
			insert(target, p2, anchor);
			insert(target, t17, anchor);
			insert(target, p3, anchor);
			insert(target, t18, anchor);
			insert(target, h31, anchor);
			insert(target, t20, anchor);
			insert(target, p4, anchor);
			insert(target, t22, anchor);
			insert(target, p5, anchor);
			insert(target, t25, anchor);
			insert(target, p6, anchor);
			insert(target, t28, anchor);
			insert(target, p7, anchor);
			insert(target, t37, anchor);
			insert(target, p8, anchor);
			insert(target, t40, anchor);
			insert(target, p9, anchor);
			insert(target, t45, anchor);
			insert(target, p10, anchor);
			insert(target, t50, anchor);
			insert(target, p11, anchor);
			insert(target, t51, anchor);
			insert(target, h32, anchor);
			insert(target, t53, anchor);
			insert(target, p12, anchor);
			insert(target, t64, anchor);
			insert(target, p13, anchor);
			insert(target, t65, anchor);
			insert(target, p14, anchor);
			insert(target, t67, anchor);
			insert(target, p15, anchor);
			insert(target, t68, anchor);
			insert(target, h33, anchor);
			insert(target, t70, anchor);
			insert(target, p16, anchor);
			insert(target, t72, anchor);
			insert(target, p17, anchor);
			insert(target, t73, anchor);
			insert(target, p18, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(h30);
			if (detaching) detach(t1);
			if (detaching) detach(p0);
			if (detaching) detach(t7);
			if (detaching) detach(p1);
			if (detaching) detach(t15);
			if (detaching) detach(p2);
			if (detaching) detach(t17);
			if (detaching) detach(p3);
			if (detaching) detach(t18);
			if (detaching) detach(h31);
			if (detaching) detach(t20);
			if (detaching) detach(p4);
			if (detaching) detach(t22);
			if (detaching) detach(p5);
			if (detaching) detach(t25);
			if (detaching) detach(p6);
			if (detaching) detach(t28);
			if (detaching) detach(p7);
			if (detaching) detach(t37);
			if (detaching) detach(p8);
			if (detaching) detach(t40);
			if (detaching) detach(p9);
			if (detaching) detach(t45);
			if (detaching) detach(p10);
			if (detaching) detach(t50);
			if (detaching) detach(p11);
			if (detaching) detach(t51);
			if (detaching) detach(h32);
			if (detaching) detach(t53);
			if (detaching) detach(p12);
			if (detaching) detach(t64);
			if (detaching) detach(p13);
			if (detaching) detach(t65);
			if (detaching) detach(p14);
			if (detaching) detach(t67);
			if (detaching) detach(p15);
			if (detaching) detach(t68);
			if (detaching) detach(h33);
			if (detaching) detach(t70);
			if (detaching) detach(p16);
			if (detaching) detach(t72);
			if (detaching) detach(p17);
			if (detaching) detach(t73);
			if (detaching) detach(p18);
		}
	};
}

const metadata = {
	"title": "Joseki Party",
	"slug": "joseki-party",
	"date": "2016.08.31",
	"site": "http://joseki.party/",
	"description": "The simplest game of _Baduk_, _Weiqi_, or _Go_ this side of the internet. Start a game of Go, and play with a friend simply by sending them a link. Invite people to witness your victory – or humiliating defeat depending on how good your friend is.",
	"template": "_templates/project.html",
	"block": "text",
	"type": "projects, department"
};

const { title, slug, date, site, description, template, block, type } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
export { metadata };