/* generated by Svelte v3.24.0 */
import { SvelteComponent, init, safe_not_equal } from "svelte/internal";

const metadata = {
	"title": "Lemons / Houses",
	"slug": "lemons-houses",
	"source": "https://photos.smugmug.com/Prints/Prints/i-5SP9mpX/0/0b56cd48/X2/lemons-800-X2.png",
	"alt": "Black and white print of densely packed houses, interspersed with mist and lemon blossoms.",
	"date": "2016.08.24",
	"edition": 10,
	"size": "12x19 inches",
	"media": "Risograph",
	"type": "art, risograph, edition"
};

const { title, slug, source, alt, date, edition, size, media, type } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { metadata };