/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "svelte/internal";

function create_fragment(ctx) {
	let blockquote0;
	let t1;
	let p1;
	let t3;
	let p2;
	let t5;
	let p3;
	let t7;
	let blockquote1;
	let t9;
	let blockquote2;
	let t11;
	let p6;
	let t15;
	let blockquote3;
	let t17;
	let p8;
	let t19;
	let blockquote4;
	let t21;
	let p10;
	let t23;
	let blockquote5;
	let t25;
	let p12;
	let t29;
	let blockquote6;
	let t31;
	let p14;
	let t33;
	let p15;
	let t35;
	let blockquote7;
	let t37;
	let p17;
	let t39;
	let blockquote8;
	let t41;
	let p19;
	let t47;
	let blockquote9;
	let t49;
	let p21;
	let t51;
	let blockquote10;
	let t53;
	let p23;
	let t55;
	let blockquote11;
	let t57;
	let p25;
	let t61;
	let blockquote12;
	let t63;
	let p27;
	let t65;
	let blockquote13;
	let t67;
	let p29;
	let t69;
	let blockquote14;
	let t71;
	let p31;
	let t73;
	let blockquote15;
	let t75;
	let p33;

	return {
		c() {
			blockquote0 = element("blockquote");
			blockquote0.innerHTML = `<p>… culture, in the broadest sense of the word, is good at pointing to things and naming them, but not so good at describing relationships between things. It privileges declarations, right answers, universals, and elementary particles. It is captivated by circular logics and modernist scripts that celebrate freedom and transcendent newness—narrative arcs that bend toward a utopian or dystopian ultimate.</p>`;
			t1 = space();
			p1 = element("p");
			p1.textContent = "Oof. Out the gate we’re coming out strong with a hard-eyed look at one of the major flaws of contemporary culture – this includes politics and economics as well as tech and design. This should be incisive.";
			t3 = space();
			p2 = element("p");
			p2.textContent = "Easterling sketches a mode of thinking where “Favoring succession rather than coexistence, the new right answer must kill the old right answer.” Our broader culture – and out individual outlook – is unable to hold two contradictory ideas at the same time as “correct”. Like the Highlander, there can only be one. We want to know the one right answer.";
			t5 = space();
			p3 = element("p");
			p3.textContent = "This mode of thinking and gathering knowledge – this one single idea of what “progress” entails – creates situations where we ratchet ourselves tighter and tighter into untenable situations.";
			t7 = space();
			blockquote1 = element("blockquote");
			blockquote1.innerHTML = `<p>Since the world’s big bullies and bulletproof forms of power—superbugs like Trump, Kim, Putin, and Bibi, or free-zone agglomerations of corporate power—thrive on this oscillation between loop and binary, it is as if there is nothing to counter them—only more ways of fighting and being right and providing the rancor that nourishes their violence. Is it possible to drop through a trapdoor and exit these logics?</p>`;
			t9 = space();
			blockquote2 = element("blockquote");
			blockquote2.innerHTML = `<p>… A radical proposal has no traction, because nothing is new and nothing is right.</p>`;
			t11 = space();
			p6 = element("p");
			p6.innerHTML = `Holy shiiiit. Easterling is rejecting the core premise of so many TED talks and thought leaders. There is no new way. There is no right answer. The only way forward lies in ambiguity. This immediately calls to mind Nim Wunnans <a href="http://conceptuallabor.com/" rel="nofollow">Theory of Conceptual Labor</a>, where he identifies that the core location of “doing good work” is necessary defined by and situated within ambiguity.`;
			t15 = space();
			blockquote3 = element("blockquote");
			blockquote3.innerHTML = `<p>There is no end or modernist succession or moment after culture.</p>`;
			t17 = space();
			p8 = element("p");
			p8.textContent = "This makes me recall some of the essays in the White Chapel collection of writing “Time” about the meaning and function of contemporary art – how we exist now in a space of the post-contemporary, and work created now can interact with and change the meaning of work created in the past. Cut loose from any sense of linear succession, all artworks can inflect each other and grow from each other freely.";
			t19 = space();
			blockquote4 = element("blockquote");
			blockquote4.innerHTML = `<p>Clear of associations with communication technologies, medium, in this context, returns to its root, medius, meaning “middle” or “milieu.”</p>`;
			t21 = space();
			p10 = element("p");
			p10.textContent = "Easterling starts to transition here to the meat of the essay.";
			t23 = space();
			blockquote5 = element("blockquote");
			blockquote5.innerHTML = `<p>Beyond declared ideologies, here is a matrix or medium of activities and latent potentials—the undeclared dispositions that are something like culture’s muscle memory.</p>`;
			t25 = space();
			p12 = element("p");
			p12.innerHTML = `This reminds me of what Hal Foster was attempting to do in <em>Design and Crime</em>, create a “running room” for culture thats less bounded by what Easterling calls “loops and binaries”.`;
			t29 = space();
			blockquote6 = element("blockquote");
			blockquote6.innerHTML = `<p>you see things with names and hear humans speaking words but those things cannot be comprehended in the absence of a thousand other affective cues and relative positions between things in context</p>`;
			t31 = space();
			p14 = element("p");
			p14.textContent = "Context, a broad gestalt understanding, becomes the key to successfully navigating and manipulating the medium. The complex tangle of objects relationships and affordances create a map of the possible, one that’s as broad as a colorspace and – lacking any defined set of instructions – just as open and possible.";
			t33 = space();
			p15 = element("p");
			p15.textContent = "This way of thinking is shocking to me – it so clearly describes my own way of working that the recognition is deeply surprising. Familiar and new – it’s interesting to see my own way of thinking described in such a clear way.";
			t35 = space();
			blockquote7 = element("blockquote");
			blockquote7.innerHTML = `<p>Turning the sound down on those declarations, it is also easier to detect the difference between what an organization is saying and what it is doing, and how organizations decouple their messages and ideologies from their real activities, underlying motivations, and structuring logics.</p>`;
			t37 = space();
			p17 = element("p");
			p17.textContent = "Meaning is created and divined by comprehending or being receptive to the whole. Everything – and everything connections between – becomes semantic. Language and marked declarations of meaning are quite possible unreliable narrators of this type of experience.";
			t39 = space();
			blockquote8 = element("blockquote");
			blockquote8.innerHTML = `<p>The disposition of any organization makes some things possible and some things impossible.</p>`;
			t41 = space();
			p19 = element("p");
			p19.innerHTML = `God damn Easterling! Just go out there and say it. This is <em>deeply</em> related to my critique of <a href="/bibliography/lencioni/five-disfunctions"><em>The Five Dysfunctions of a Team</em></a>. The structure and gestalt of an organization is the primary defining factor of dysfunction and success, rather than any individual actor.`;
			t47 = space();
			blockquote9 = element("blockquote");
			blockquote9.innerHTML = `<p>For instance, being right is a really bad idea on the other side. It is too weak. It does not work against gurus and totalitarian bullies. Maybe culture’s spectacular failures, together with the underexploited powers of the medium, could inspire alternative ways to register the imagination—other approaches to form-making and design in any discipline.</p>`;
			t49 = space();
			p21 = element("p");
			p21.textContent = "Focus on right-ness is a core value of our system, and look at the results of that system. Sheesh.";
			t51 = space();
			blockquote10 = element("blockquote");
			blockquote10.innerHTML = `<p>Entanglements are more productive than solutions.</p>`;
			t53 = space();
			p23 = element("p");
			p23.textContent = "This is just … such an articulation against everything that silicon valley tech-fetishism espouses. This is so compelling.";
			t55 = space();
			blockquote11 = element("blockquote");
			blockquote11.innerHTML = `<p>Design in the medium is less like making a thing and more like having your hands on the faders and toggles of organization.</p>`;
			t57 = space();
			p25 = element("p");
			p25.innerHTML = `This is deeply related to the thesis I outlined in <a href="/texts/how-to-design-while-developing">How to Design While Developing</a>.`;
			t61 = space();
			blockquote12 = element("blockquote");
			blockquote12.innerHTML = `<p>It is the design of interdependencies, chemistries, chain reactions. It benefits from an artistic curiosity about spatial wiring or reagents in spatial mixtures. You are designing not only a single object but a platform for inflecting populations of objects or setting up relative potentials within them. You are comfortable with dynamic markers and unfinished processes.</p>`;
			t63 = space();
			p27 = element("p");
			p27.textContent = "This is perhaps the single best definition of web design I have very seen.";
			t65 = space();
			blockquote13 = element("blockquote");
			blockquote13.innerHTML = `<p>And maybe the existence or content of a problem is less important than the interplay between problems. Failure is a limitless wilderness for design ecologies.</p>`;
			t67 = space();
			p29 = element("p");
			p29.textContent = "Welcome to … the Internet. This is exactly how we generate successful work in the medium of the internet.";
			t69 = space();
			blockquote14 = element("blockquote");
			blockquote14.innerHTML = `<p>If an unsafe factory collapses or burns, there is an event to mark the violence, but in countless factories or industrial parks that do not buckle under the weight of their own denial, there is no event, no drawn sword. There is only latent temperament—the constant aggression of blatantly imbalanced power dynamics. The potential for either concentrating or distributing power; the potential for escalating or reducing violence.</p>`;
			t71 = space();
			p31 = element("p");
			p31.textContent = "Easterling here defines the struggle with the modern web. Is there a connection here to what it would mean to practice an ethical web design? Not to have answers or solutions, but to navigate the tangled web of semantics in ways that reduce the potential for violence, that ratchet slowly towards an ethical stance";
			t73 = space();
			blockquote15 = element("blockquote");
			blockquote15.innerHTML = `<p>But if it has any hope of effecting change, it manipulates the organization as well as the instrumental narrative that attends it with moves that are potentially sneakier or more politically agile.</p>`;
			t75 = space();
			p33 = element("p");
			p33.innerHTML = `A key takeaway here is that in order to produce effective work <em>in the world</em> part of the work needs to be done <em>to the organization</em>. Changing the organization and structure around the work is the only way to produce work that is different or more effective.`;
		},
		m(target, anchor) {
			insert(target, blockquote0, anchor);
			insert(target, t1, anchor);
			insert(target, p1, anchor);
			insert(target, t3, anchor);
			insert(target, p2, anchor);
			insert(target, t5, anchor);
			insert(target, p3, anchor);
			insert(target, t7, anchor);
			insert(target, blockquote1, anchor);
			insert(target, t9, anchor);
			insert(target, blockquote2, anchor);
			insert(target, t11, anchor);
			insert(target, p6, anchor);
			insert(target, t15, anchor);
			insert(target, blockquote3, anchor);
			insert(target, t17, anchor);
			insert(target, p8, anchor);
			insert(target, t19, anchor);
			insert(target, blockquote4, anchor);
			insert(target, t21, anchor);
			insert(target, p10, anchor);
			insert(target, t23, anchor);
			insert(target, blockquote5, anchor);
			insert(target, t25, anchor);
			insert(target, p12, anchor);
			insert(target, t29, anchor);
			insert(target, blockquote6, anchor);
			insert(target, t31, anchor);
			insert(target, p14, anchor);
			insert(target, t33, anchor);
			insert(target, p15, anchor);
			insert(target, t35, anchor);
			insert(target, blockquote7, anchor);
			insert(target, t37, anchor);
			insert(target, p17, anchor);
			insert(target, t39, anchor);
			insert(target, blockquote8, anchor);
			insert(target, t41, anchor);
			insert(target, p19, anchor);
			insert(target, t47, anchor);
			insert(target, blockquote9, anchor);
			insert(target, t49, anchor);
			insert(target, p21, anchor);
			insert(target, t51, anchor);
			insert(target, blockquote10, anchor);
			insert(target, t53, anchor);
			insert(target, p23, anchor);
			insert(target, t55, anchor);
			insert(target, blockquote11, anchor);
			insert(target, t57, anchor);
			insert(target, p25, anchor);
			insert(target, t61, anchor);
			insert(target, blockquote12, anchor);
			insert(target, t63, anchor);
			insert(target, p27, anchor);
			insert(target, t65, anchor);
			insert(target, blockquote13, anchor);
			insert(target, t67, anchor);
			insert(target, p29, anchor);
			insert(target, t69, anchor);
			insert(target, blockquote14, anchor);
			insert(target, t71, anchor);
			insert(target, p31, anchor);
			insert(target, t73, anchor);
			insert(target, blockquote15, anchor);
			insert(target, t75, anchor);
			insert(target, p33, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(blockquote0);
			if (detaching) detach(t1);
			if (detaching) detach(p1);
			if (detaching) detach(t3);
			if (detaching) detach(p2);
			if (detaching) detach(t5);
			if (detaching) detach(p3);
			if (detaching) detach(t7);
			if (detaching) detach(blockquote1);
			if (detaching) detach(t9);
			if (detaching) detach(blockquote2);
			if (detaching) detach(t11);
			if (detaching) detach(p6);
			if (detaching) detach(t15);
			if (detaching) detach(blockquote3);
			if (detaching) detach(t17);
			if (detaching) detach(p8);
			if (detaching) detach(t19);
			if (detaching) detach(blockquote4);
			if (detaching) detach(t21);
			if (detaching) detach(p10);
			if (detaching) detach(t23);
			if (detaching) detach(blockquote5);
			if (detaching) detach(t25);
			if (detaching) detach(p12);
			if (detaching) detach(t29);
			if (detaching) detach(blockquote6);
			if (detaching) detach(t31);
			if (detaching) detach(p14);
			if (detaching) detach(t33);
			if (detaching) detach(p15);
			if (detaching) detach(t35);
			if (detaching) detach(blockquote7);
			if (detaching) detach(t37);
			if (detaching) detach(p17);
			if (detaching) detach(t39);
			if (detaching) detach(blockquote8);
			if (detaching) detach(t41);
			if (detaching) detach(p19);
			if (detaching) detach(t47);
			if (detaching) detach(blockquote9);
			if (detaching) detach(t49);
			if (detaching) detach(p21);
			if (detaching) detach(t51);
			if (detaching) detach(blockquote10);
			if (detaching) detach(t53);
			if (detaching) detach(p23);
			if (detaching) detach(t55);
			if (detaching) detach(blockquote11);
			if (detaching) detach(t57);
			if (detaching) detach(p25);
			if (detaching) detach(t61);
			if (detaching) detach(blockquote12);
			if (detaching) detach(t63);
			if (detaching) detach(p27);
			if (detaching) detach(t65);
			if (detaching) detach(blockquote13);
			if (detaching) detach(t67);
			if (detaching) detach(p29);
			if (detaching) detach(t69);
			if (detaching) detach(blockquote14);
			if (detaching) detach(t71);
			if (detaching) detach(p31);
			if (detaching) detach(t73);
			if (detaching) detach(blockquote15);
			if (detaching) detach(t75);
			if (detaching) detach(p33);
		}
	};
}

const metadata = {
	"title": "Medium Design",
	"slug": "medium-design",
	"author": "Keller Easterling",
	"year": 2020,
	"source": "https://www.e-flux.com/journal/106/312238/medium-design/",
	"tags": "design",
	"thesis": "To design effectively with a medium, knowledge and solutions to a system are less effective than understanding the relationships within the system, and how to manipulate and adjust those systems to move towards a set of outcomes.",
	"type": "annotation, bibliography"
};

const { title, slug, author, year, source, tags, thesis, type } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
export { metadata };