/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "svelte/internal";

function create_fragment(ctx) {
	let p0;
	let t0;
	let p1;
	let t1;
	let p2;
	let t2;
	let p3;
	let t3;
	let p4;
	let t4;
	let p5;

	return {
		c() {
			p0 = element("p");
			p0.innerHTML = `<img src="./title.png" alt="At the Mountains of Madness">`;
			t0 = space();
			p1 = element("p");
			p1.innerHTML = `<img src="./start-reading.png" alt="At the Mountains of Madness">`;
			t1 = space();
			p2 = element("p");
			p2.innerHTML = `<img src="./chapter-title.png" alt="At the Mountains of Madness">`;
			t2 = space();
			p3 = element("p");
			p3.innerHTML = `<img src="./text.png" alt="At the Mountains of Madness">`;
			t3 = space();
			p4 = element("p");
			p4.innerHTML = `<img src="./chapter-title-inverted.png" alt="At the Mountains of Madness">`;
			t4 = space();
			p5 = element("p");
			p5.innerHTML = `<img src="./text-inverted.png" alt="At the Mountains of Madness">`;
		},
		m(target, anchor) {
			insert(target, p0, anchor);
			insert(target, t0, anchor);
			insert(target, p1, anchor);
			insert(target, t1, anchor);
			insert(target, p2, anchor);
			insert(target, t2, anchor);
			insert(target, p3, anchor);
			insert(target, t3, anchor);
			insert(target, p4, anchor);
			insert(target, t4, anchor);
			insert(target, p5, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p0);
			if (detaching) detach(t0);
			if (detaching) detach(p1);
			if (detaching) detach(t1);
			if (detaching) detach(p2);
			if (detaching) detach(t2);
			if (detaching) detach(p3);
			if (detaching) detach(t3);
			if (detaching) detach(p4);
			if (detaching) detach(t4);
			if (detaching) detach(p5);
		}
	};
}

const metadata = {
	"title": "At the Mountains of Madness",
	"site": "http://miskatonic.nikolas.ws/",
	"date": "2014-06-21T00:00:00.000Z",
	"description": "An exercise in digital publishing, this edition of _At the Mountains of Madness_ by H.P. Lovecraft is a free, open, public domain text. Created as a high-end, web-native publication in response to a personal desire the read the text online, and being unable to find a version that did the original physical publication any justice.",
	"type": "projects, department",
	"archived": true
};

const { title, site, date, description, type, archived } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
export { metadata };http://www.lonegoosepress.com",
	"date": "2015-03-14T00:00:00.000Z",
	"description": "A catalog and ecommerce website for for the Eugene, Oregon based letterpress studio lone goose press.",
	"type": "projects, department",
	"archived": true
};

const { title, site, date, description, type, archived } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
export { metadata };Rosskopf's](http://morganrosskopf.com/) solo show at [One Grand Gallery](http://www.onegrandgallery.com/) commissioned by the artist and the gallery.",
	"type": "art, riso, edition, book",
	"archived": true
};

const { title, date, description, type, archived } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
export { metadata };of time. This collapsing of image is present in all the work, sometimes being composited, sliced apart, and re-composited until the original is entirely removed and a new image exists over its deconstructed framework. Each piece is based upon a single system of relationships and gridded framework co-opted from a typographic practice, reflecting the hard infrastructures of construction and communication that contemporary society is built on. Writing systems are a central component of my work in that they allow an individual to create a permanent mark of their thoughts on the environment. Writing is a direct externalization of identity. Through abstraction of city form and iconography, I seek to reflect the abstract forces that fundamentally guide our globalized world.";
			t17 = space();
			p7 = element("p");
			p7.innerHTML = `<img src="./replica01.jpg" alt="An Exact Replica of a Thing that Never Existed">`;
			t18 = space();
			figcaption4 = element("figcaption");
			figcaption4.textContent = "An Exact Replica of a Thing that Never Existed, Etching, Silkscreen, 2012";
			t20 = space();
			p8 = element("p");
			p8.innerHTML = `<img src="./replica02.jpg" alt="An Exact Replica of a Thing that Never Existed">`;
			t21 = space();
			figcaption5 = element("figcaption");
			figcaption5.textContent = "An Exact Replica of a Thing that Never Existed, Detail";
			t23 = space();
			p9 = element("p");
			p9.textContent = "I am focusing on the blurred distinction between human geography and physical geography as it comments on post-modern urbanism, issues of sprawl and lack of specificity and physical place in a post-geographic, globalized system of living on a human level. I examine the connections to local environment and context within the global city. With these prints, I seek to examine the current relevancy of both physical and informational infrastructures, from highways to the internet, shipping lines to global markets, built environments to typographic systems, in defining place and self.";
			t25 = space();
			p10 = element("p");
			p10.innerHTML = `<img src="./capacities01.jpg" alt="The Capacities of the Human Body to Locate Itself">`;
			t26 = space();
			figcaption6 = element("figcaption");
			figcaption6.textContent = "The Capacities of the Human Body to Locate Itself, Etching, Giclee, 2012";
			t28 = space();
			p11 = element("p");
			p11.innerHTML = `<img src="./capacities02.jpg" alt="The Capacities of the Human Body to Locate Itself">`;
			t29 = space();
			figcaption7 = element("figcaption");
			figcaption7.textContent = "The Capacities of the Human Body to Locate Itself, Detail";
			t31 = space();
			h4 = element("h4");
			h4.textContent = "Bibliography";
			t33 = space();
			h50 = element("h5");
			h50.innerHTML = `Gibson, William. “Dead Man Sings”, <em>Distrust That Particular Flavor</em>. New York: Putnam Group, 2012`;
			t37 = space();
			p12 = element("p");
			p12.textContent = "A short essay discussing the unnoticed shift that human life took when analog, and later digital, media started to elongate our collective memories. Interesting discussion of what effect locating identities and human narratives outside of our head, or oral traditions, can have on a society.";
			t39 = space();
			h51 = element("h5");
			h51.innerHTML = `Gibson, William. <em>Pattern Recognition</em>. New York: Berkley Publishing Group, 2003`;
			t43 = space();
			p13 = element("p");
			p13.textContent = "Gibson’s seventh novel. A densely layered quasi-narrative dealing with problems of geographic specificity, globalized fashion trends and trade, the power of corporations in the realm of cultural influence, and the capabilities of pareidolia and obsession.";
			t45 = space();
			h52 = element("h5");
			h52.innerHTML = `Calvino, Italo. <em>Invisible Cities</em>. Orlando: Harcourt, 1974`;
			t49 = space();
			p14 = element("p");
			p14.textContent = "Calvino describes cities are as they felt and lived in experientially rather than descriptively or objectively. He raises issues of mirroring, reflecting, and the relationships between person and place. As he dissects and lays bare a single city, questions of semantic reasoning and possibilities of communication are raised.";
			t51 = space();
			h53 = element("h5");
			h53.innerHTML = `Dear, Michael, Flusty, Steven. “Postmodern Urbanism.” <em>Annals of the Association of American Geographers</em>, Vol. 88, No. 1 (Mar., 1998), pp. 50-72`;
			t55 = space();
			p15 = element("p");
			p15.textContent = "Dear and Flusty set out to describe how the modernist Chicago School theory of urbanism does not hold with post-modern geographies, in particular Los Angeles. They describe the city structure of Los Angeles in relation to landscape opportunities and necessities, population demographics, and market pressures of late-stage capitalism. They go on to describe how the physical regions of the post-modern city are indicative of social structures, and how these hierarchies either enforce or subvert cultural patterns. They forecast a city with the post-modern structures of Los Angeles taken to dystopian extremes.";
		},
		m(target, anchor) {
			insert(target, p0, anchor);
			insert(target, t0, anchor);
			insert(target, figcaption0, anchor);
			insert(target, t2, anchor);
			insert(target, p1, anchor);
			insert(target, t4, anchor);
			insert(target, p2, anchor);
			insert(target, t5, anchor);
			insert(target, figcaption1, anchor);
			insert(target, t7, anchor);
			insert(target, p3, anchor);
			insert(target, t9, anchor);
			insert(target, p4, anchor);
			insert(target, t10, anchor);
			insert(target, figcaption2, anchor);
			insert(target, t12, anchor);
			insert(target, p5, anchor);
			insert(target, t13, anchor);
			insert(target, figcaption3, anchor);
			insert(target, t15, anchor);
			insert(target, p6, anchor);
			insert(target, t17, anchor);
			insert(target, p7, anchor);
			insert(target, t18, anchor);
			insert(target, figcaption4, anchor);
			insert(target, t20, anchor);
			insert(target, p8, anchor);
			insert(target, t21, anchor);
			insert(target, figcaption5, anchor);
			insert(target, t23, anchor);
			insert(target, p9, anchor);
			insert(target, t25, anchor);
			insert(target, p10, anchor);
			insert(target, t26, anchor);
			insert(target, figcaption6, anchor);
			insert(target, t28, anchor);
			insert(target, p11, anchor);
			insert(target, t29, anchor);
			insert(target, figcaption7, anchor);
			insert(target, t31, anchor);
			insert(target, h4, anchor);
			insert(target, t33, anchor);
			insert(target, h50, anchor);
			insert(target, t37, anchor);
			insert(target, p12, anchor);
			insert(target, t39, anchor);
			insert(target, h51, anchor);
			insert(target, t43, anchor);
			insert(target, p13, anchor);
			insert(target, t45, anchor);
			insert(target, h52, anchor);
			insert(target, t49, anchor);
			insert(target, p14, anchor);
			insert(target, t51, anchor);
			insert(target, h53, anchor);
			insert(target, t55, anchor);
			insert(target, p15, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p0);
			if (detaching) detach(t0);
			if (detaching) detach(figcaption0);
			if (detaching) detach(t2);
			if (detaching) detach(p1);
			if (detaching) detach(t4);
			if (detaching) detach(p2);
			if (detaching) detach(t5);
			if (detaching) detach(figcaption1);
			if (detaching) detach(t7);
			if (detaching) detach(p3);
			if (detaching) detach(t9);
			if (detaching) detach(p4);
			if (detaching) detach(t10);
			if (detaching) detach(figcaption2);
			if (detaching) detach(t12);
			if (detaching) detach(p5);
			if (detaching) detach(t13);
			if (detaching) detach(figcaption3);
			if (detaching) detach(t15);
			if (detaching) detach(p6);
			if (detaching) detach(t17);
			if (detaching) detach(p7);
			if (detaching) detach(t18);
			if (detaching) detach(figcaption4);
			if (detaching) detach(t20);
			if (detaching) detach(p8);
			if (detaching) detach(t21);
			if (detaching) detach(figcaption5);
			if (detaching) detach(t23);
			if (detaching) detach(p9);
			if (detaching) detach(t25);
			if (detaching) detach(p10);
			if (detaching) detach(t26);
			if (detaching) detach(figcaption6);
			if (detaching) detach(t28);
			if (detaching) detach(p11);
			if (detaching) detach(t29);
			if (detaching) detach(figcaption7);
			if (detaching) detach(t31);
			if (detaching) detach(h4);
			if (detaching) detach(t33);
			if (detaching) detach(h50);
			if (detaching) detach(t37);
			if (detaching) detach(p12);
			if (detaching) detach(t39);
			if (detaching) detach(h51);
			if (detaching) detach(t43);
			if (detaching) detach(p13);
			if (detaching) detach(t45);
			if (detaching) detach(h52);
			if (detaching) detach(t49);
			if (detaching) detach(p14);
			if (detaching) detach(t51);
			if (detaching) detach(h53);
			if (detaching) detach(t55);
			if (detaching) detach(p15);
		}
	};
}

const metadata = {
	"title": "Axioms",
	"date": "2013-5-20",
	"description": "Bachelor of Fine Arts in Printmaking thesis. An exploration of examining the experiences and memories of the built city through print, collage, and drawing.",
	"type": "art, printmaking",
	"archived": true
};

const { title, date, description, type, archived } = metadata;

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
export { metadata };